services:
  angular:
    build:
      context: Angular-CustomerDetailsService
    ports:
        - 4200:80

  java:
    build:
      context: Java-CustomerDetailsService
      target: builder
    ports:
      - 8080:8080

    # volumes:
    #   - ./angular:/project
    #   - /project/node_modules